version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: app-nginx
    ports:
      - "${NGINX_PORT}:8090"
    volumes:
      - ./:/var/www
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    environment:
      - NGINX_PORT=8090
      - NGINX_CONF=/etc/nginx/conf.d/default.conf

  db:
    platform: linux/x86_64
    image: mysql:5.6.47
    container_name: app-db
    ports:
      - "3306:3306"
    volumes:
      - ./etc/infrastructure/mysql/my.cnf:/etc/mysql/my.cnf
      - ./etc/database/base.sql:/docker-entrypoint-initdb.d/base.sql
    networks:
      - my-network

  php:
    image: php:latest
    container_name: app-php
    volumes:
      - ./:/var/www
    networks:
      - my-network

networks:
  my-network:
    external:
      name: my-network
